services:
  web:
    build: .
    container_name: auremont_web
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,web,auremont.edu,www.auremont.edu

  nginx:
    image: nginx:latest
    container_name: auremont_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./nginx.conf:/etc/nginx/conf.d/auremont_university.conf
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: