# Generated by Django 5.2.7 on 2025-10-26 08:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the banner (for admin reference)",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("hero", 44)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("image", "Image"),
                                        ("color", "Solid Color"),
                                        ("gradient", "Gradient"),
                                        ("video", "Background Video"),
                                    ],
                                    "help_text": "Select the banner background type.",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Used when type = image",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "MP4/WebM video URL for background video (auto loops).",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Solid background color (e.g. #001F3F).",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Gradient start color",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Gradient end color", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("to right", "Left → Right"),
                                        ("to bottom", "Top → Bottom"),
                                        ("to top right", "Diagonal"),
                                    ],
                                    "help_text": "Direction of gradient if enabled.",
                                },
                            ),
                            7: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "required": False},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Overlay hex color", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.FloatBlock",
                                (),
                                {"default": 0.5, "max_value": 1.0, "min_value": 0.0},
                            ),
                            10: (
                                "wagtail.blocks.FloatBlock",
                                (),
                                {
                                    "default": 0.0,
                                    "max_value": 10.0,
                                    "min_value": 0.0,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 140, "required": True},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Font size (e.g. 48px, 3rem, clamp(2rem,5vw,4rem))",
                                    "required": False,
                                },
                            ),
                            15: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Title color (hex or CSS variable)",
                                    "required": False,
                                },
                            ),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("300", "Light"),
                                        ("400", "Regular"),
                                        ("500", "Medium"),
                                        ("600", "Semi-Bold"),
                                        ("700", "Bold"),
                                    ],
                                    "help_text": "Font weight for title and subtitle.",
                                },
                            ),
                            18: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "required": False},
                            ),
                            19: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("top", "Top"),
                                        ("center", "Center"),
                                        ("bottom", "Bottom"),
                                    ]
                                },
                            ),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "900px",
                                    "help_text": "Max width for text container (e.g. 900px)",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "8rem",
                                    "help_text": "Padding top (e.g. 8rem)",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "8rem",
                                    "help_text": "Padding bottom (e.g. 8rem)",
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Button text",
                                    "max_length": 40,
                                    "required": True,
                                },
                            ),
                            25: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional icon class (e.g., fa-solid fa-arrow-right)",
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                        ("ghost", "Ghost"),
                                        ("link", "Text Link"),
                                    ]
                                },
                            ),
                            28: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("none", "None"),
                                        ("grow", "Grow"),
                                        ("shrink", "Shrink"),
                                        ("underline", "Underline"),
                                        ("shadow", "Shadow Glow"),
                                    ],
                                    "help_text": "Hover animation style for the button",
                                },
                            ),
                            29: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Open link in new tab",
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 24),
                                        ("url", 25),
                                        ("icon", 26),
                                        ("style", 27),
                                        ("hover_effect", 28),
                                        ("open_in_new_tab", 29),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"max_num": 3, "required": False},
                            ),
                            32: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Automatically scroll down after delay.",
                                    "required": False,
                                },
                            ),
                            33: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "default": 5,
                                    "help_text": "Seconds before auto-scroll",
                                    "required": False,
                                },
                            ),
                            34: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("none", "None"),
                                        ("fade", "Fade In"),
                                        ("slide-up", "Slide Up"),
                                        ("typewriter", "Typewriter"),
                                        ("zoom", "Zoom In"),
                                    ]
                                },
                            ),
                            35: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "1s",
                                    "help_text": "CSS animation duration (e.g. 1s)",
                                    "required": False,
                                },
                            ),
                            36: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "0s",
                                    "help_text": "Animation delay (e.g. 0.3s)",
                                    "required": False,
                                },
                            ),
                            37: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            38: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Font size for mobile view",
                                    "required": False,
                                },
                            ),
                            39: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Mobile padding (e.g. 4rem 2rem)",
                                    "required": False,
                                },
                            ),
                            40: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Custom CSS class", "required": False},
                            ),
                            41: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Custom HTML ID", "required": False},
                            ),
                            42: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Inline CSS for fine control",
                                    "required": False,
                                },
                            ),
                            43: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Inline JavaScript or animation logic",
                                    "required": False,
                                },
                            ),
                            44: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("background_type", 0),
                                        ("background_image", 1),
                                        ("background_video_url", 2),
                                        ("background_color", 3),
                                        ("gradient_start", 4),
                                        ("gradient_end", 5),
                                        ("gradient_direction", 6),
                                        ("overlay_enabled", 7),
                                        ("overlay_color", 8),
                                        ("overlay_opacity", 9),
                                        ("overlay_blur", 10),
                                        ("title", 11),
                                        ("subtitle", 12),
                                        ("tagline", 13),
                                        ("title_font_size", 14),
                                        ("subtitle_font_size", 15),
                                        ("tagline_font_size", 15),
                                        ("title_color", 16),
                                        ("subtitle_color", 15),
                                        ("tagline_color", 15),
                                        ("font_weight", 17),
                                        ("text_shadow", 18),
                                        ("vertical_alignment", 19),
                                        ("horizontal_alignment", 20),
                                        ("content_max_width", 21),
                                        ("padding_top", 22),
                                        ("padding_bottom", 23),
                                        ("full_height", 7),
                                        ("parallax", 18),
                                        ("ctas", 31),
                                        ("button_alignment", 20),
                                        ("scroll_indicator", 18),
                                        ("auto_scroll", 32),
                                        ("scroll_delay", 33),
                                        ("text_animation", 34),
                                        ("animation_duration", 35),
                                        ("animation_delay", 36),
                                        ("animation_loop", 18),
                                        ("mobile_background_image", 37),
                                        ("mobile_hide_overlay", 18),
                                        ("mobile_text_centered", 7),
                                        ("mobile_title_size", 38),
                                        ("mobile_padding", 39),
                                        ("css_class", 40),
                                        ("custom_id", 41),
                                        ("custom_css", 42),
                                        ("custom_js", 43),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Hero Banner Content",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Banner",
                "verbose_name_plural": "Hero Banners",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a hero banner to display on this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.herobanner",
            ),
        ),
    ]
