# Generated by Django 5.2.7 on 2025-10-26 09:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_herobanner_alter_homepage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herobanner",
            name="content",
            field=wagtail.fields.StreamField(
                [("hero", 46)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Image"),
                                ("color", "Solid Color"),
                                ("gradient", "Gradient"),
                                ("video", "Background Video"),
                            ],
                            "help_text": "Select the banner background type.",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Used when type = image (select from media library)",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when type = image (external image URL)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "MP4/WebM video URL for background video (auto loops).",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Solid background color (e.g. #001F3F).",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Gradient start color", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Gradient end color", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("to right", "Left → Right"),
                                ("to bottom", "Top → Bottom"),
                                ("to top right", "Diagonal"),
                            ],
                            "help_text": "Direction of gradient if enabled.",
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Overlay hex color", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.5, "max_value": 1.0, "min_value": 0.0},
                    ),
                    11: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "default": 0.0,
                            "max_value": 10.0,
                            "min_value": 0.0,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 140, "required": True},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    14: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Font size (e.g. 48px, 3rem, clamp(2rem,5vw,4rem))",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title color (hex or CSS variable)",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300", "Light"),
                                ("400", "Regular"),
                                ("500", "Medium"),
                                ("600", "Semi-Bold"),
                                ("700", "Bold"),
                            ],
                            "help_text": "Font weight for title and subtitle.",
                        },
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("center", "Center"),
                                ("bottom", "Bottom"),
                            ]
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "900px",
                            "help_text": "Max width for text container (e.g. 900px)",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "8rem",
                            "help_text": "Padding top (e.g. 8rem)",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "8rem",
                            "help_text": "Padding bottom (e.g. 8rem)",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button text",
                            "max_length": 40,
                            "required": True,
                        },
                    ),
                    26: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon class (e.g., fa-solid fa-arrow-right)",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                                ("link", "Text Link"),
                            ]
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("grow", "Grow"),
                                ("shrink", "Shrink"),
                                ("underline", "Underline"),
                                ("shadow", "Shadow Glow"),
                            ],
                            "help_text": "Hover animation style for the button",
                        },
                    ),
                    30: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Open link in new tab",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 25),
                                ("url", 26),
                                ("icon", 27),
                                ("style", 28),
                                ("hover_effect", 29),
                                ("open_in_new_tab", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {"max_num": 3, "required": False},
                    ),
                    33: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Automatically scroll down after delay.",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 5,
                            "help_text": "Seconds before auto-scroll",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade", "Fade In"),
                                ("slide-up", "Slide Up"),
                                ("typewriter", "Typewriter"),
                                ("zoom", "Zoom In"),
                            ]
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "1s",
                            "help_text": "CSS animation duration (e.g. 1s)",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0s",
                            "help_text": "Animation delay (e.g. 0.3s)",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    39: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "External image URL for mobile",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Font size for mobile view", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mobile padding (e.g. 4rem 2rem)",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Custom CSS class", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Custom HTML ID", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Inline CSS for fine control", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Inline JavaScript or animation logic",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_type", 0),
                                ("background_image", 1),
                                ("background_image_url", 2),
                                ("background_video_url", 3),
                                ("background_color", 4),
                                ("gradient_start", 5),
                                ("gradient_end", 6),
                                ("gradient_direction", 7),
                                ("overlay_enabled", 8),
                                ("overlay_color", 9),
                                ("overlay_opacity", 10),
                                ("overlay_blur", 11),
                                ("title", 12),
                                ("subtitle", 13),
                                ("tagline", 14),
                                ("title_font_size", 15),
                                ("subtitle_font_size", 16),
                                ("tagline_font_size", 16),
                                ("title_color", 17),
                                ("subtitle_color", 16),
                                ("tagline_color", 16),
                                ("font_weight", 18),
                                ("text_shadow", 19),
                                ("vertical_alignment", 20),
                                ("horizontal_alignment", 21),
                                ("content_max_width", 22),
                                ("padding_top", 23),
                                ("padding_bottom", 24),
                                ("full_height", 8),
                                ("parallax", 19),
                                ("ctas", 32),
                                ("button_alignment", 21),
                                ("scroll_indicator", 19),
                                ("auto_scroll", 33),
                                ("scroll_delay", 34),
                                ("text_animation", 35),
                                ("animation_duration", 36),
                                ("animation_delay", 37),
                                ("animation_loop", 19),
                                ("mobile_background_image", 38),
                                ("mobile_background_image_url", 39),
                                ("mobile_hide_overlay", 19),
                                ("mobile_text_centered", 8),
                                ("mobile_title_size", 40),
                                ("mobile_padding", 41),
                                ("css_class", 42),
                                ("custom_id", 43),
                                ("custom_css", 44),
                                ("custom_js", 45),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Hero Banner Content",
            ),
        ),
    ]
