# Generated by Django 5.0.14 on 2025-10-26 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_herobanner_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a hero banner to display on this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homepages",
                to="home.herobanner",
            ),
        ),
    ]
