# Generated by Django 5.0.14 on 2025-10-26 09:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_homepage_hero_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
