# Generated by Django 5.2.7 on 2025-10-26 09:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navbar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this navigation bar (for admin reference)",
                        max_length=100,
                    ),
                ),
                (
                    "navigation_items",
                    wagtail.fields.StreamField(
                        [("nav_item", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Navigation item label",
                                    "max_length": 50,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to an internal page",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "External URL (use instead of page)",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Open link in new tab",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 0),
                                        ("page", 1),
                                        ("external_url", 2),
                                        ("open_in_new_tab", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Navigation Items",
                    ),
                ),
                (
                    "sticky",
                    models.BooleanField(
                        help_text="Make navbar stick to top of page when scrolling"
                    ),
                ),
                (
                    "transparent",
                    models.BooleanField(
                        help_text="Make navbar transparent on homepage hero section"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo for the navbar",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Bar",
                "verbose_name_plural": "Navigation Bars",
                "ordering": ["name"],
            },
        ),
    ]
