# Generated by Django 5.0.14 on 2025-10-26 10:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_navbar"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="navbar",
            field=wagtail.fields.StreamField(
                [("navbar", 30)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Auremont University",
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Label for the dropdown item",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the dropdown item", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 4), ("link", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {"help_text": "Submenu items.", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon CSS class (e.g. fa-solid fa-book).",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("glow", "Glow"),
                                ("underline", "Underline"),
                                ("gold-underline", "Gold Underline"),
                                ("scale", "Scale Up"),
                            ]
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 2),
                                ("link", 3),
                                ("dropdown_items", 7),
                                ("icon_class", 8),
                                ("hover_effect", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"help_text": "Main menu items.", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#001F3F",
                            "help_text": "Navbar background color.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#FFFFFF",
                            "help_text": "Navbar text color.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#FFD700",
                            "help_text": "Hover color (gold).",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "1rem",
                            "help_text": "Top/Bottom padding (e.g. 1rem).",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "2rem",
                            "help_text": "Left/Right padding (e.g. 2rem).",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "1rem",
                            "help_text": "Font size for menu items.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5px", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Animate color on scroll.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 100,
                            "help_text": "Scroll pixels before color transition.",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "900px", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("slide-down", "Slide Down"),
                                ("zoom", "Zoom In"),
                            ],
                            "help_text": "Navbar load animation.",
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5s", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "ease-in-out", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Custom CSS overrides.", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Custom JS or jQuery scripts.",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional AJAX logic for navbar links (e.g. smooth load of content).",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo_image", 0),
                                ("university_name", 1),
                                ("menu_items", 11),
                                ("background_color", 12),
                                ("text_color", 13),
                                ("hover_color", 14),
                                ("transparent_on_load", 15),
                                ("nav_shadow", 15),
                                ("sticky_navbar", 15),
                                ("logo_alignment", 16),
                                ("menu_alignment", 16),
                                ("padding_y", 17),
                                ("padding_x", 18),
                                ("font_size", 19),
                                ("letter_spacing", 20),
                                ("scroll_transition", 21),
                                ("scroll_threshold", 22),
                                ("collapse_on_click", 15),
                                ("mobile_breakpoint", 23),
                                ("load_animation", 24),
                                ("animation_duration", 25),
                                ("animation_easing", 26),
                                ("custom_css", 27),
                                ("custom_js", 28),
                                ("ajax_behavior", 29),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Navigation Bar",
            ),
        ),
        migrations.DeleteModel(
            name="Navbar",
        ),
    ]
