# Generated by Django 5.0.14 on 2025-10-26 10:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_homepage_navbar_delete_navbar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herobanner",
            name="content",
            field=wagtail.fields.StreamField(
                [("hero", 69)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("image", "Image"),
                                ("color", "Solid Color"),
                                ("gradient", "Gradient"),
                                ("video", "Video"),
                                ("kenburns", "Ken Burns Zoom"),
                            ]
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "to right", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "rgba(0,0,0,0.3)", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.5, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.0, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 140, "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "clamp(2rem,5vw,4rem)", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1.25rem", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1rem", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#ffffff", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#f5f5f5", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#dddddd", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional custom font family", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300", "Light"),
                                ("400", "Regular"),
                                ("500", "Medium"),
                                ("600", "Semi-Bold"),
                                ("700", "Bold"),
                            ]
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0px", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("center", "Center"),
                                ("bottom", "Bottom"),
                            ]
                        },
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "900px", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "8rem 2rem", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "16/9", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.3, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Banner width (e.g. 100%, 1200px)",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Banner height (e.g. 500px, 60vh)",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Minimum height (e.g. 400px)", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum height (e.g. 800px)", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border radius (e.g. 10px)", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0px",
                            "help_text": "Border width (e.g. 2px)",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("solid", "Solid"),
                                ("dashed", "Dashed"),
                                ("dotted", "Dotted"),
                                ("double", "Double"),
                                ("none", "None"),
                            ],
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border color (e.g. #000000)", "required": False},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 20px 0)", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 60, "required": True},
                    ),
                    38: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                                ("gradient", "Gradient"),
                                ("glass", "Glass Effect"),
                                ("link", "Text Link"),
                            ]
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("grow", "Grow"),
                                ("shrink", "Shrink"),
                                ("underline", "Underline"),
                                ("shadow", "Shadow Glow"),
                                ("pulse", "Pulse"),
                                ("tilt", "Tilt"),
                            ]
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Used if style=gradient", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "45deg", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFD700", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Button width (e.g. 200px, 100%)",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Button height (e.g. 50px)", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Minimum width (e.g. 150px)", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Minimum height (e.g. 40px)", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum width (e.g. 300px)", "required": False},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum height (e.g. 60px)", "required": False},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "8px",
                            "help_text": "Border radius (e.g. 5px, 50%)",
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "2px",
                            "help_text": "Border width (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0.9rem 1.8rem",
                            "help_text": "Padding (e.g. 10px 20px)",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 10px 0)", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "1rem",
                            "help_text": "Font size (e.g. 16px)",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300", "Light"),
                                ("400", "Regular"),
                                ("500", "Medium"),
                                ("600", "Semi-Bold"),
                                ("700", "Bold"),
                            ],
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("uppercase", "Uppercase"),
                                ("lowercase", "Lowercase"),
                                ("capitalize", "Capitalize"),
                            ],
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Letter spacing (e.g. 1px)", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Custom CSS styles (e.g. box-shadow: 2px 2px 5px rgba(0,0,0,0.3);)",
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 37),
                                ("url", 38),
                                ("icon", 3),
                                ("style", 39),
                                ("hover_effect", 40),
                                ("open_in_new_tab", 21),
                                ("gradient_start", 41),
                                ("gradient_end", 3),
                                ("gradient_angle", 42),
                                ("glow_color", 43),
                                ("width", 44),
                                ("height", 45),
                                ("min_width", 46),
                                ("min_height", 47),
                                ("max_width", 48),
                                ("max_height", 49),
                                ("border_radius", 50),
                                ("border_width", 51),
                                ("border_style", 34),
                                ("border_color", 35),
                                ("padding", 52),
                                ("margin", 53),
                                ("font_size", 54),
                                ("font_weight", 55),
                                ("text_transform", 56),
                                ("letter_spacing", 57),
                                ("custom_css", 58),
                            ]
                        ],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {"max_num": 4, "required": False},
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade", "Fade In"),
                                ("slide-up", "Slide Up"),
                                ("slide-left", "Slide Left"),
                                ("typewriter", "Typewriter"),
                                ("zoom", "Zoom In"),
                                ("kenburns", "Ken Burns"),
                            ]
                        },
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1s", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0s", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("blur-in", "Blur In"),
                                ("glow", "Glow Fade"),
                                ("split-text", "Split Text Reveal"),
                            ]
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "4rem 1.5rem", "required": False},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional section ID to scroll to.",
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "required": False},
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("dark", "Dark"),
                                ("light", "Light"),
                                ("gold", "Gold Accent"),
                                ("auremont", "Auremont Classic"),
                            ]
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_type", 0),
                                ("background_image", 1),
                                ("background_image_url", 2),
                                ("background_video_url", 2),
                                ("background_color", 3),
                                ("gradient_start", 3),
                                ("gradient_end", 3),
                                ("gradient_direction", 4),
                                ("overlay_enabled", 5),
                                ("overlay_color", 6),
                                ("overlay_opacity", 7),
                                ("overlay_blur", 8),
                                ("blur_intensity", 8),
                                ("title", 9),
                                ("subtitle", 10),
                                ("tagline", 11),
                                ("title_font_size", 12),
                                ("subtitle_font_size", 13),
                                ("tagline_font_size", 14),
                                ("title_color", 15),
                                ("subtitle_color", 16),
                                ("tagline_color", 17),
                                ("font_family", 18),
                                ("font_weight", 19),
                                ("letter_spacing", 20),
                                ("text_shadow", 21),
                                ("vertical_alignment", 22),
                                ("horizontal_alignment", 23),
                                ("content_max_width", 24),
                                ("content_padding", 25),
                                ("full_height", 5),
                                ("aspect_ratio", 26),
                                ("parallax", 21),
                                ("scroll_parallax_strength", 27),
                                ("width", 28),
                                ("height", 29),
                                ("min_height", 30),
                                ("max_height", 31),
                                ("border_radius", 32),
                                ("border_width", 33),
                                ("border_style", 34),
                                ("border_color", 35),
                                ("margin", 36),
                                ("ctas", 60),
                                ("button_alignment", 23),
                                ("button_spacing", 14),
                                ("text_animation", 61),
                                ("animation_duration", 62),
                                ("animation_delay", 63),
                                ("animation_loop", 21),
                                ("entry_effect", 64),
                                ("mobile_background_image", 1),
                                ("mobile_background_image_url", 2),
                                ("mobile_hide_overlay", 21),
                                ("mobile_title_size", 3),
                                ("mobile_padding", 65),
                                ("scroll_indicator", 21),
                                ("scroll_down_target", 66),
                                ("auto_scroll", 21),
                                ("scroll_delay", 67),
                                ("mouse_parallax_effect", 21),
                                ("hover_glow", 21),
                                ("theme", 68),
                                ("css_class", 3),
                                ("custom_id", 3),
                                ("custom_css", 11),
                                ("custom_js", 11),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Hero Banner Content",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="navbar",
            field=wagtail.fields.StreamField(
                [("navbar", 49)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Auremont University", "required": True},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional short text for mega-menu style",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 4),
                                ("link", 6),
                                ("icon_class", 2),
                                ("description", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {"required": False}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("glow", "Glow"),
                                ("underline", "Underline"),
                                ("gold-underline", "Gold Underline"),
                                ("scale", "Scale Up"),
                                ("slide-bg", "Slide Background"),
                            ]
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu item width (e.g. 120px, auto)",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu item height (e.g. 50px)",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Padding (e.g. 10px 15px)", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 0 5px)", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Font size (e.g. 16px)", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300", "Light"),
                                ("400", "Regular"),
                                ("500", "Medium"),
                                ("600", "Semi-Bold"),
                                ("700", "Bold"),
                            ],
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 4),
                                ("link", 5),
                                ("dropdown_items", 9),
                                ("icon_class", 2),
                                ("hover_effect", 10),
                                ("is_button", 11),
                                ("button_style", 12),
                                ("width", 13),
                                ("height", 14),
                                ("padding", 15),
                                ("margin", 16),
                                ("font_size", 17),
                                ("font_weight", 18),
                            ]
                        ],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {"required": False}),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#001F3F", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFFFFF", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFD700", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#003366", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 10.0, "required": False},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1rem", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "2rem", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5px", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "60px", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Navbar width (e.g. 100%, 1200px)",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Navbar height (e.g. 80px)", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum width (e.g. 1400px)", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border radius (e.g. 5px)", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0px",
                            "help_text": "Border width (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("solid", "Solid"),
                                ("dashed", "Dashed"),
                                ("dotted", "Dotted"),
                                ("double", "Double"),
                                ("none", "None"),
                            ],
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border color (e.g. #000000)", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 0 auto)", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 100, "required": False},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "900px", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-bars", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-xmark", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.2, "required": False},
                    ),
                    44: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("slide-down", "Slide Down"),
                                ("zoom", "Zoom In"),
                            ]
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5s", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "ease-in-out", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("classic", "Classic"),
                                ("modern", "Modern"),
                                ("glass", "Glass"),
                                ("gold", "Gold"),
                            ]
                        },
                    ),
                    48: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo_image", 0),
                                ("university_name", 1),
                                ("tagline", 2),
                                ("logo_alignment", 3),
                                ("menu_items", 20),
                                ("menu_alignment", 3),
                                ("enable_search", 21),
                                ("enable_language_switcher", 11),
                                ("background_color", 22),
                                ("text_color", 23),
                                ("hover_color", 24),
                                ("gradient_background", 11),
                                ("gradient_start", 22),
                                ("gradient_end", 25),
                                ("backdrop_blur", 11),
                                ("blur_strength", 26),
                                ("transparent_on_load", 21),
                                ("nav_shadow", 21),
                                ("sticky_navbar", 21),
                                ("padding_y", 27),
                                ("padding_x", 28),
                                ("font_size", 27),
                                ("letter_spacing", 29),
                                ("logo_size", 30),
                                ("width", 31),
                                ("height", 32),
                                ("max_width", 33),
                                ("border_radius", 34),
                                ("border_width", 35),
                                ("border_style", 36),
                                ("border_color", 37),
                                ("margin", 38),
                                ("scroll_transition", 21),
                                ("scroll_threshold", 39),
                                ("collapse_on_click", 21),
                                ("mobile_breakpoint", 40),
                                ("hamburger_icon", 41),
                                ("close_icon", 42),
                                ("dropdown_hover_delay", 43),
                                ("load_animation", 44),
                                ("animation_duration", 45),
                                ("animation_easing", 46),
                                ("theme", 47),
                                ("custom_css", 48),
                                ("custom_js", 48),
                                ("ajax_behavior", 48),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Navigation Bar",
            ),
        ),
    ]
