# Generated by Django 5.0.14 on 2025-10-26 11:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_herobanner_content_alter_homepage_navbar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="navbar",
            field=wagtail.fields.StreamField(
                [("navbar", 47)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Auremont University", "required": True},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the main menu item",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon class (e.g. fa-solid fa-book)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 4), ("url", 7), ("icon_class", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {"max_num": 10, "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon for the column",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("column_title", 6), ("links", 10), ("icon_class", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "Up to 4 columns for mega menu",
                            "max_num": 4,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon for the menu item",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable mega menu for this item",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 4),
                                ("link", 5),
                                ("mega_menu_columns", 13),
                                ("icon_class", 14),
                                ("is_mega_menu", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"required": False}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#001F3F", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFFFFF", "required": False},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFD700", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#003366", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 10.0, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1rem", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "2rem", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5px", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "60px", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Navbar width (e.g. 100%, 1200px)",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Navbar height (e.g. 80px)", "required": False},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum width (e.g. 1400px)", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border radius (e.g. 5px)", "required": False},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0px",
                            "help_text": "Border width (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("solid", "Solid"),
                                ("dashed", "Dashed"),
                                ("dotted", "Dotted"),
                                ("double", "Double"),
                                ("none", "None"),
                            ],
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border color (e.g. #000000)", "required": False},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 0 auto)", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 100, "required": False},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "900px", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-bars", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-xmark", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.2, "required": False},
                    ),
                    42: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("slide-down", "Slide Down"),
                                ("zoom", "Zoom In"),
                            ]
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5s", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "ease-in-out", "required": False},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("classic", "Classic"),
                                ("modern", "Modern"),
                                ("glass", "Glass"),
                                ("gold", "Gold"),
                            ]
                        },
                    ),
                    46: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo_image", 0),
                                ("university_name", 1),
                                ("tagline", 2),
                                ("logo_alignment", 3),
                                ("menu_items", 17),
                                ("menu_alignment", 3),
                                ("enable_search", 18),
                                ("enable_language_switcher", 19),
                                ("background_color", 20),
                                ("text_color", 21),
                                ("hover_color", 22),
                                ("gradient_background", 19),
                                ("gradient_start", 20),
                                ("gradient_end", 23),
                                ("backdrop_blur", 19),
                                ("blur_strength", 24),
                                ("transparent_on_load", 18),
                                ("nav_shadow", 18),
                                ("sticky_navbar", 18),
                                ("padding_y", 25),
                                ("padding_x", 26),
                                ("font_size", 25),
                                ("letter_spacing", 27),
                                ("logo_size", 28),
                                ("width", 29),
                                ("height", 30),
                                ("max_width", 31),
                                ("border_radius", 32),
                                ("border_width", 33),
                                ("border_style", 34),
                                ("border_color", 35),
                                ("margin", 36),
                                ("scroll_transition", 18),
                                ("scroll_threshold", 37),
                                ("collapse_on_click", 18),
                                ("mobile_breakpoint", 38),
                                ("hamburger_icon", 39),
                                ("close_icon", 40),
                                ("dropdown_hover_delay", 41),
                                ("load_animation", 42),
                                ("animation_duration", 43),
                                ("animation_easing", 44),
                                ("theme", 45),
                                ("custom_css", 46),
                                ("custom_js", 46),
                                ("ajax_behavior", 46),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Navigation Bar",
            ),
        ),
    ]
