# Generated by Django 5.0.14 on 2025-10-26 11:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_homepage_navbar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="navbar",
            field=wagtail.fields.StreamField(
                [("navbar", 62)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Auremont University", "required": True},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the main menu item",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon class (e.g. fa-solid fa-book)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 4), ("url", 7), ("icon_class", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {"max_num": 10, "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon for the column",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("column_title", 6), ("links", 10), ("icon_class", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "Up to 4 columns for mega menu",
                            "max_num": 4,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon for the menu item",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable mega menu for this item",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 4),
                                ("link", 5),
                                ("mega_menu_columns", 13),
                                ("icon_class", 14),
                                ("is_mega_menu", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"required": False}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Search...",
                            "help_text": "Placeholder text for the search input",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/search/",
                            "help_text": "URL endpoint for search requests",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable toggle behavior (compact icon that expands to input field)",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable auto-suggest dropdown powered by AJAX",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL endpoint for auto-suggest AJAX requests",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Width of the search input when expanded (e.g. 200px, 100%)",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Height of the search input (e.g. 40px)",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "4px",
                            "help_text": "Border radius of the search input (e.g. 5px, 50%)",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "1px",
                            "help_text": "Border width of the search input (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#CCCCCC",
                            "help_text": "Border color of the search input (e.g. #000000)",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#D4AF37",
                            "help_text": "Border color when input is focused (e.g. #D4AF37 for gold)",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#FFFFFF",
                            "help_text": "Background color of the search input (e.g. #FFFFFF)",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#000000",
                            "help_text": "Text color of the search input (e.g. #000000)",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#666666",
                            "help_text": "Color of the search icon (e.g. #666666)",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("placeholder_text", 19),
                                ("search_endpoint_url", 20),
                                ("enable_toggle", 21),
                                ("enable_auto_suggest", 22),
                                ("auto_suggest_endpoint", 23),
                                ("input_width", 24),
                                ("input_height", 25),
                                ("border_radius", 26),
                                ("border_width", 27),
                                ("border_color", 28),
                                ("focus_border_color", 29),
                                ("background_color", 30),
                                ("text_color", 31),
                                ("icon_color", 32),
                            ]
                        ],
                        {"required": False},
                    ),
                    34: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#001F3F", "required": False},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFFFFF", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFD700", "required": False},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#003366", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 10.0, "required": False},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1rem", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "2rem", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5px", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "60px", "required": False},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Navbar width (e.g. 100%, 1200px)",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Navbar height (e.g. 80px)", "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum width (e.g. 1400px)", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border radius (e.g. 5px)", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0px",
                            "help_text": "Border width (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("solid", "Solid"),
                                ("dashed", "Dashed"),
                                ("dotted", "Dotted"),
                                ("double", "Double"),
                                ("none", "None"),
                            ],
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border color (e.g. #000000)", "required": False},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 0 auto)", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 100, "required": False},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "900px", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-bars", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-xmark", "required": False},
                    ),
                    56: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.2, "required": False},
                    ),
                    57: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("slide-down", "Slide Down"),
                                ("zoom", "Zoom In"),
                            ]
                        },
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5s", "required": False},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "ease-in-out", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("classic", "Classic"),
                                ("modern", "Modern"),
                                ("glass", "Glass"),
                                ("gold", "Gold"),
                            ]
                        },
                    ),
                    61: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo_image", 0),
                                ("university_name", 1),
                                ("tagline", 2),
                                ("logo_alignment", 3),
                                ("menu_items", 17),
                                ("menu_alignment", 3),
                                ("enable_search", 18),
                                ("search_settings", 33),
                                ("enable_language_switcher", 34),
                                ("background_color", 35),
                                ("text_color", 36),
                                ("hover_color", 37),
                                ("gradient_background", 34),
                                ("gradient_start", 35),
                                ("gradient_end", 38),
                                ("backdrop_blur", 34),
                                ("blur_strength", 39),
                                ("transparent_on_load", 18),
                                ("nav_shadow", 18),
                                ("sticky_navbar", 18),
                                ("padding_y", 40),
                                ("padding_x", 41),
                                ("font_size", 40),
                                ("letter_spacing", 42),
                                ("logo_size", 43),
                                ("width", 44),
                                ("height", 45),
                                ("max_width", 46),
                                ("border_radius", 47),
                                ("border_width", 48),
                                ("border_style", 49),
                                ("border_color", 50),
                                ("margin", 51),
                                ("scroll_transition", 18),
                                ("scroll_threshold", 52),
                                ("collapse_on_click", 18),
                                ("mobile_breakpoint", 53),
                                ("hamburger_icon", 54),
                                ("close_icon", 55),
                                ("dropdown_hover_delay", 56),
                                ("load_animation", 57),
                                ("animation_duration", 58),
                                ("animation_easing", 59),
                                ("theme", 60),
                                ("custom_css", 61),
                                ("custom_js", 61),
                                ("ajax_behavior", 61),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Navigation Bar",
            ),
        ),
    ]
