# Generated by Django 5.0.14 on 2025-10-26 11:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_homepage_navbar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="navbar",
            field=wagtail.fields.StreamField(
                [("navbar", 78)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Auremont University", "required": True},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link for the main menu item",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    7: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon class (e.g. fa-solid fa-book)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 4), ("url", 7), ("icon_class", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {"max_num": 10, "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon for the column",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("column_title", 6), ("links", 10), ("icon_class", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "Up to 4 columns for mega menu",
                            "max_num": 4,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional icon for the menu item",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable mega menu for this item",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 4),
                                ("link", 5),
                                ("mega_menu_columns", 13),
                                ("icon_class", 14),
                                ("is_mega_menu", 15),
                            ]
                        ],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (16,), {"required": False}),
                    18: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Search...",
                            "help_text": "Placeholder text for the search input",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/search/",
                            "help_text": "URL endpoint for search requests",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable toggle behavior (compact icon that expands to input field)",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Enable auto-suggest dropdown powered by AJAX",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL endpoint for auto-suggest AJAX requests",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Width of the search input when expanded (e.g. 200px, 100%)",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Height of the search input (e.g. 40px)",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "4px",
                            "help_text": "Border radius of the search input (e.g. 5px, 50%)",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "1px",
                            "help_text": "Border width of the search input (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#CCCCCC",
                            "help_text": "Border color of the search input (e.g. #000000)",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#D4AF37",
                            "help_text": "Border color when input is focused (e.g. #D4AF37 for gold)",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#FFFFFF",
                            "help_text": "Background color of the search input (e.g. #FFFFFF)",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#000000",
                            "help_text": "Text color of the search input (e.g. #000000)",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#666666",
                            "help_text": "Color of the search icon (e.g. #666666)",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("placeholder_text", 19),
                                ("search_endpoint_url", 20),
                                ("enable_toggle", 21),
                                ("enable_auto_suggest", 22),
                                ("auto_suggest_endpoint", 23),
                                ("input_width", 24),
                                ("input_height", 25),
                                ("border_radius", 26),
                                ("border_width", 27),
                                ("border_color", 28),
                                ("focus_border_color", 29),
                                ("background_color", 30),
                                ("text_color", 31),
                                ("icon_color", 32),
                            ]
                        ],
                        {"required": False},
                    ),
                    34: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/accounts/login/",
                            "help_text": "URL for login page",
                            "required": False,
                        },
                    ),
                    35: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/accounts/register/",
                            "help_text": "URL for registration page",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/accounts/profile/",
                            "help_text": "URL for user profile page",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/accounts/settings/",
                            "help_text": "URL for user settings page",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "/accounts/logout/",
                            "help_text": "URL for logout functionality",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show user avatar if available",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("initials", "User Initials"),
                                ("icon", "Default Icon"),
                                ("none", "No Fallback"),
                            ],
                            "help_text": "Fallback display when no avatar is available",
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "40px",
                            "help_text": "Size of the avatar (e.g. 40px, 2.5rem)",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "50%",
                            "help_text": "Border radius of the avatar (e.g. 50% for circle, 4px for rounded)",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "200px",
                            "help_text": "Width of the dropdown menu (e.g. 200px, 15rem)",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#FFFFFF",
                            "help_text": "Background color of the dropdown menu",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#333333",
                            "help_text": "Text color of the dropdown menu",
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#F5F5F5",
                            "help_text": "Background color on hover",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "8px",
                            "help_text": "Border radius of the dropdown menu",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0 4px 6px rgba(0,0,0,0.1)",
                            "help_text": "Box shadow for the dropdown menu",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("login_link", 34),
                                ("register_link", 35),
                                ("profile_link", 36),
                                ("settings_link", 37),
                                ("logout_link", 38),
                                ("show_avatar", 39),
                                ("avatar_fallback", 40),
                                ("avatar_size", 41),
                                ("avatar_border_radius", 42),
                                ("dropdown_width", 43),
                                ("dropdown_background", 44),
                                ("dropdown_text_color", 45),
                                ("dropdown_hover_background", 46),
                                ("dropdown_border_radius", 47),
                                ("dropdown_shadow", 48),
                            ]
                        ],
                        {"required": False},
                    ),
                    50: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#001F3F", "required": False},
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFFFFF", "required": False},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#FFD700", "required": False},
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "#003366", "required": False},
                    ),
                    55: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 10.0, "required": False},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "1rem", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "2rem", "required": False},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5px", "required": False},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "60px", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Navbar width (e.g. 100%, 1200px)",
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Navbar height (e.g. 80px)", "required": False},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Maximum width (e.g. 1400px)", "required": False},
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border radius (e.g. 5px)", "required": False},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "0px",
                            "help_text": "Border width (e.g. 1px)",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("solid", "Solid"),
                                ("dashed", "Dashed"),
                                ("dotted", "Dotted"),
                                ("double", "Double"),
                                ("none", "None"),
                            ],
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Border color (e.g. #000000)", "required": False},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Margin (e.g. 0 auto)", "required": False},
                    ),
                    68: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 100, "required": False},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "900px", "required": False},
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-bars", "required": False},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "fa-solid fa-xmark", "required": False},
                    ),
                    72: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {"default": 0.2, "required": False},
                    ),
                    73: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("fade-in", "Fade In"),
                                ("slide-down", "Slide Down"),
                                ("zoom", "Zoom In"),
                            ]
                        },
                    ),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "0.5s", "required": False},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "ease-in-out", "required": False},
                    ),
                    76: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("classic", "Classic"),
                                ("modern", "Modern"),
                                ("glass", "Glass"),
                                ("gold", "Gold"),
                            ]
                        },
                    ),
                    77: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo_image", 0),
                                ("university_name", 1),
                                ("tagline", 2),
                                ("logo_alignment", 3),
                                ("menu_items", 17),
                                ("menu_alignment", 3),
                                ("enable_search", 18),
                                ("search_settings", 33),
                                ("enable_user_menu", 18),
                                ("user_menu_settings", 49),
                                ("enable_language_switcher", 50),
                                ("background_color", 51),
                                ("text_color", 52),
                                ("hover_color", 53),
                                ("gradient_background", 50),
                                ("gradient_start", 51),
                                ("gradient_end", 54),
                                ("backdrop_blur", 50),
                                ("blur_strength", 55),
                                ("transparent_on_load", 18),
                                ("nav_shadow", 18),
                                ("sticky_navbar", 18),
                                ("padding_y", 56),
                                ("padding_x", 57),
                                ("font_size", 56),
                                ("letter_spacing", 58),
                                ("logo_size", 59),
                                ("width", 60),
                                ("height", 61),
                                ("max_width", 62),
                                ("border_radius", 63),
                                ("border_width", 64),
                                ("border_style", 65),
                                ("border_color", 66),
                                ("margin", 67),
                                ("scroll_transition", 18),
                                ("scroll_threshold", 68),
                                ("collapse_on_click", 18),
                                ("mobile_breakpoint", 69),
                                ("hamburger_icon", 70),
                                ("close_icon", 71),
                                ("dropdown_hover_delay", 72),
                                ("load_animation", 73),
                                ("animation_duration", 74),
                                ("animation_easing", 75),
                                ("theme", 76),
                                ("custom_css", 77),
                                ("custom_js", 77),
                                ("ajax_behavior", 77),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Navigation Bar",
            ),
        ),
    ]
